### ISSUE TITLE
Replace episode favourites view page

### ISSUE THREAD

**Issue by olotintemitope** [andela/suyabay#199] opened 2016-03-09 08:21 UTC
I observed that the episode favourite page still uses old layout, which makes the view not be consistent when to compare with  single episode page.

**Comment by johnkariuki** [comment] 2016-03-09 08:22
@andela-tolotin this is a duplicate of the issue I had raised earlier when we paired with you.
I will close the other one.

**Closed as completed** 2016-03-11 06:18 UTC
Labels: chore
